//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afex_videos
{
    using System;
    using System.Collections.Generic;
    
    public partial class videos
    {
        public int Id { get; set; }
        public string video { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
